version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - "./data/db:/data/db"
    ports:
      - 38128:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    environment:
      - TZ=Asia/Shanghai


  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    environment:
      - TZ=Asia/Shanghai
